version: "3.8"

services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        ports:
            - 443:443
        restart: always
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
            args:
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always