version: "3.8"

services:
    nginx:
        depends_on:
            - "wordpress"
        container_name: nginx
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        ports:
            - 443:443
        networks:
            - my_network
        restart: always
        volumes:
          - /home/ygaiero/wordpress:/var/www/wordpress

    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile          
            args:
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER_ADMIN: ${MYSQL_USER_ADMIN}
                MYSQL_PASSWORD_ADMIN: ${MYSQL_PASSWORD_ADMIN}
        networks:
            - my_network
        restart: always
        expose:
            - "3306"
        env_file:
            - .env
        volumes:
            - /home/ygaiero/mariadb:/var/lib/mysql

    wordpress:
        depends_on:
            -  "mariadb"
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        env_file:
            - .env
        networks:
            - my_network
        restart: always
        expose:
            - "9000"
        volumes:
          - /home/ygaiero/wordpress:/var/www/wordpress
        
        
networks:
    my_network:
        driver: bridge
        